scrape_linkedin_posts:
  description: >
    Search for LinkedIn posts related to AI topics (LLM, GenAI, RAG, etc.) 
    from the last 7 days using Google search. Focus on posts with high 
    engagement metrics.
  expected_output: >
    A structured dataset containing:
    - Post URLs and content
    - Engagement metrics (reactions, comments, shares)
    - AI topic classifications
    - Timestamp information
  agent: linkedin_scrape_agent

analyze_engagement:
  description: >
    Evaluate the engagement metrics of LinkedIn posts collected, focusing on reactions, comments, and shares to prioritize topics for further analysis.
  expected_output: >
    An analysis report with ranked topics and detailed engagement breakdowns.
  agent: linkedin_interaction_analyze_agent

generate_ideas:
  description: >
    Use engagement data to brainstorm and recommend the most promising topics for content creation. Collaborate with LLMs to refine suggestions.
  expected_output: >
    A curated list of top-performing topics with creative insights for content strategy.
  agent: brainstorm_agent

conduct_web_search:
  description: >
    Perform a detailed web search to find blogs, articles, and research papers relevant to the chosen topic. Utilize tools like Google Serper and ArXiv.
  expected_output: >
    A structured list of references, categorized by source type, relevance, and reliability.
  agent: web_search_agent

create_post:
  description: >
   Use insights from the "Creative Insights Generator" and references from the "Knowledge Discovery Specialist" 
    to create a professional LinkedIn post. The content should align with trending topics, audience expectations, 
    and the platform's best practices. Incorporate multimedia elements like images or graphics to enhance engagement.
  expected_output: >
    """A single LinkedIn post in JSON format with two fields:
            - title: The post title
            - content: The main post content"""
  agent: post_create_agent

notify_user:
  description: >
   Send this LinkedIn post for review via Slack using the following format:
            Input format: A dictionary containing 'context' with the post data.
            The post data should include 'title' and 'content' fields."""
    Send the LinkedIn post draft to the user via Slack for review. The notification should include 
    the complete post content and allow for user feedback.
  expected_output: >
   Confirmation of the Slack notification being sent
  agent: notification_agent

publish_post:
  description: >
    Share the approved LinkedIn post on the user's profile with appropriate formatting and timing.
  expected_output: >
    A successfully published LinkedIn post with optimized reach and engagement.

share_linkedin_post:
  description: >
    Share the approved LinkedIn post using the LinkedIn API.
    Ensure professional formatting and proper API integration.
  expected_output: >
    Confirmation of successful post sharing on LinkedIn with post URL
  agent: share_agent
  context:
    - create_post