scrape_linkedin_posts:
  description: >
    Using the LinkedIn Scrape Tool, collect posts from the user's feed that are
    related to AI topics (LLM, GenAI, RAG, etc.). Focus on posts from the last 4 days
    and analyze their engagement metrics. Collect details including post content,
    reactions, comments, shares, and matched AI topics.
  expected_output: >
    A structured dataset containing:
    - Post content and URLs
    - Engagement metrics (reactions, comments, shares)
    - AI topic classifications
    - Timestamp information
  agent: linkedin_scrape_agent
analyze_engagement:
  description: >
    Evaluate the engagement metrics of LinkedIn posts collected, focusing on reactions, comments, and shares to prioritize topics for further analysis.
  expected_output: >
    An analysis report with ranked topics and detailed engagement breakdowns.

generate_ideas:
  description: >
    Use engagement data to brainstorm and recommend the most promising topics for content creation. Collaborate with LLMs to refine suggestions.
  expected_output: >
    A curated list of top-performing topics with creative insights for content strategy.

conduct_web_search:
  description: >
    Perform a detailed web search to find blogs, articles, and research papers relevant to the chosen topic. Utilize tools like Google Serper and ArXiv.
  expected_output: >
    A structured list of references, categorized by source type, relevance, and reliability.

create_post:
  description: >
    Use insights from the "Creative Insights Generator" and references from the "Knowledge Discovery Specialist" 
    to create a professional LinkedIn post. The content should align with trending topics, audience expectations, 
    and the platform's best practices. Incorporate multimedia elements like images or graphics to enhance engagement.
  expected_output: >
    A finalized LinkedIn post draft, including a title, body text, and optional multimedia elements,
    stored in a structured format for review and sharing.
  inputs:
    - creative_insights: >
        Key themes, ideas, and suggestions generated by the "Creative Insights Generator."
    - research_references: >
        Supporting data, references, and context from the "Knowledge Discovery Specialist."
  outputs:
    - linkedin_post: >
        A structured LinkedIn post draft, containing text and optionally associated multimedia assets.
  prerequisites:
    - generate_ideas  # Task provided by the "Creative Insights Generator."
    - conduct_web_search  # Task provided by the "Knowledge Discovery Specialist."

notify_user:
  description: Notify user with LinkedIn post draft for review
  expected_output: Email notification status
  agent: notification_agent
  context: 
    - create_post
  output_dict:
    status: str
    email_sent: bool
    recipient: str

publish_post:
  description: >
    Share the approved LinkedIn post on the user's profile with appropriate formatting and timing.
  expected_output: >
    A successfully published LinkedIn post with optimized reach and engagement.